config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  post '/', to: 'todos#create'

  resources :projects, only: [:destroy]
  resources :todos, only: [:show, :create, :update, :destroy]
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @project = Project.all
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to "/"
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index

  end

  def create
    @project = Project.find(params[:project_id].values)
    @todo = @project.map{|x| x.todos.create(todo_params)}
    redirect_to root_url
  end
  
  def update
    @todo = Todo.find(params[:id])
    @isCompleted = if @todo.isCompleted == true then false else true end
    @todo.update({:isCompleted => @isCompleted})
    redirect_to "/"
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to "/"
  end
 
  private
    def todo_params
      params.require(:todo).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/to_do_helper.rb
module ToDoHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/new.html.erb
<h2>Новый проект</h2>

app/views/todos/index.html.erb
<!DOCTYPE html >
<html>
 <head>
  <meta charset="utf-8" />
   <title>Список задач</title>
   <link href="blue.css.scss" rel="stylesheets/vendor">
   <link href="select2.css" rel="stylesheets/vendor">
  </head>
 <body>
  <div id="Header">
   <h1>Задачи</h1>
   <p> <%=image_tag("plus.png", alt: "Plus Image")%> </p>
  </div>

  <div id= "show">
  <% Project.all.each do |project| %>
   <div class="project">
    <div id= "title">
      <p> <%= project.title %> 
          <!--<%= link_to 'XXX', project,
              method: :delete, :id => "delete" %></p>-->
    </div>
    <ul>
    <% project.todos.each do |todo| %>       
	<%= form_for todo, method: :patch do |f|%>		
	<p> <%= check_box( "", todo.id, {checked: todo.isCompleted}) %>
        <label for= "_<%=todo.id %>", class=strike-text<%=todo.isCompleted %>><%= todo.text %></label>
	<%= f.submit '', :id => "fsbch" %>
	<%= link_to 'X', todo,
              method: :delete, :id => "delete" %></p>
        <% end %>
    <% end %>
    </ul>
   </div>
  <% end %>
  </div>
	
  <div id="div1">
   <%= form_for Todo.create, id: "f1" do |f| %>
    <h2>Новая задача</h2>
    <p> <%= f.text_field :text, id:"newtasktf", placeholder:"Название задачи..." %>
        <%= f.check_box :isCompleted, id: "ch1" %>
    </p>
    <p> <%= collection_select(:project_id, :project_id, Project.all, :id, :title) %>
	<%= f.submit '', :class => "hidden", :id => "fsb" %>
    </p>
    <p> <a id="a1" href="javascript:void(0)" >Отмена</a>
	<%= link_to 'Ок', href= "javascript:void(0)", id:"a2" %>
    </p>
   <% end %>
  </div>
 </body>
</html>

app/views/welcome/index.html.erb
<h1>Задачи</h1>

<p>
    <%=image_tag("plus.jpg", alt: "Plus Image")%>
</p>

<% Project.all.each do |project| %>
<p>
  <%= project.title %>
</p>
<ul>
<% project.todos.each do |todo| %>
  <li> <%= todo.text %> </li>
<% end %>
</ul>
<% end %>

<div id="div1">
<%= form_for project_path Todo.create, id: "f1"  do |f| %>
  <h2>Новая задача</h2>
  <p>
    <%= f.text_field :text %>
    <%= f.check_box :isCompleted, id: "ch1" %>
  </p>
  <p>
    <%= f.collection_select(:project_id, Project.all, :id, :title) %>
    <%= f.submit %>
  </p>
  <p>
  <a id="a1" href="javascript:void(0)" >Отмена</a>
  <%= link_to 'Ок', href="javascript:void(0)", id:"a2" %>
  </p>
<% end %>
</div>